---
http:
  routers:
    cbeaver:
      rule: Host(`cbeaver.jgalabs.dk`)
      entrypoints: [websecure]
      tls:
        certresolver: cfresolver
      service: cbeaver
      middlewares: [sablier-cbeaver@file]
  services:
    cbeaver:
      loadBalancer:
        servers:
          - url: http://cloudbeaver:8978/
  middlewares:
    sablier-cbeaver:
      plugin:
        sablier:
          group: cbeaver
          dynamic:
            displayName: service
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 30m
