---
http:
  middlewares:
    sablier-default:
      plugin:
        sablier:
          group: default
          dynamic:
            displayName: service
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 10m
    default-cache:
      plugin:
        httpCache:
          maxTtl: 300
          memory:
            limit: 100M
          excludedResponseCodes: 500-599
