---
http:
  routers:
    hoarder:
      rule: Host(`hoarder.jgalabs.dk`)
      entrypoints: [websecure]
      tls:
        certresolver: cfresolver
      service: hoarder
      middlewares: [sablier-hoarder@file]
  services:
    hoarder:
      loadBalancer:
        servers:
          - url: http://hoarder:3000/
  middlewares:
    sablier-hoarder:
      plugin:
        sablier:
          group: hoarder
          dynamic:
            displayName: Hoarder
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 10m
