---
http:
  routers:
    portainer:
      rule: Host(`pods.jgalabs.dk`)
      entrypoints: [websecure]
      tls:
        certresolver: cfresolver
      service: portainer
      middlewares: [sablier-portainer@file]
  services:
    portainer:
      loadBalancer:
        servers:
          - url: http://portainer:9000/
  middlewares:
    sablier-portainer:
      plugin:
        sablier:
          group: portainer
          dynamic:
            displayName: Portainer
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 30m
