---
services:
  minio:
    image: minio/minio:latest
    volumes: [minio_data:/data]
    networks: [traefik_public]
    env_file: [./.env-minio]
    deploy:
      replicas: 1
      labels:
        # s3 api
        - traefik.enable=true
        - traefik.http.routers.minio-api.rule=Host(`s3.jgalabs.dk`)
        - traefik.http.routers.minio-api.entrypoints=websecure
        - traefik.http.services.minio-api.loadbalancer.server.port=9000
        - traefik.http.routers.minio-api.service=minio-api
        # webui
        - traefik.http.routers.minio-console.entrypoints=websecure
        - traefik.http.services.minio-console.loadbalancer.server.port=9001
        - traefik.http.routers.minio-console.service=minio-console
    command: minio server /data --console-address ":9001"
volumes:
  minio_data:
networks:
  traefik_public:
    external: true
