---
volumes:
  postgres_data:
networks:
  traefik_public:
    external: true
secrets:
  postgres_password:
    external: true
  postgres_admin_user:
    external: true
services:
  psql:
    image: postgres:latest
    # Uncomment ports if needed and provide default values
    environment:
      - POSTGRES_USER_FILE=/run/secrets/postgres_admin_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - TZ=Europe/Copenhagen
    secrets: [postgres_admin_user, postgres_password]
    volumes: [postgres_data:/var/lib/postgresql/data]
    networks: [traefik_public]
    # ports: [5433:5432]
    deploy:
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.postgres.tls=false
        - traefik.tcp.routers.postgres.rule=HostSNI(`*`)
        - traefik.tcp.services.postgres.loadbalancer.server.port=5432
        - traefik.tcp.routers.postgres.entrypoints=dbsecure
