---
version: '3'
configs:
  traefik_static:
    file: ./traefik/traefik.yml
services:
  traefik:
    image: traefik:latest
    deploy:
      placement:
        constraints: [node.role == manager]
      mode: global
      labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`traefik.jgalabs.dk`)
        - traefik.http.routers.api.service=api@internal
        - traefik.http.routers.api.entrypoints=websecure
        - traefik.http.routers.api.tls=true
        - traefik.http.routers.api.tls.certresolver=cfresolver
        - traefik.http.services.traefik.loadbalancer.server.port=8080
    ports: [80:80, 443:443, 5432:5432]
    environment:
      - CF_API_EMAIL=jakob1379@gmail.com
      - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_dns_api_token
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/dyn:/etc/traefik/dyn
    configs:
      - source: traefik_static
        target: /etc/traefik/traefik.yml
    networks: [traefik_public]
    secrets: [cf_dns_api_token]
  sablier:
    image: sablierapp/sablier:1.8.1
    command: [start, --provider.name=swarm]
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    networks: [traefik_public]
  whoami:
    image: traefik/whoami
    networks: [traefik_public]
    deploy:
      replicas: 0
      labels:
        - traefik.docker.lbswarm=true
        - sablier.enable=true
        - sablier.group=default
  adguardhome:
    image: adguard/adguardhome:latest
    ports:
      # - "3000:3000/tcp"  # Admin dashboard port
      - 53:53/tcp  # DNS TCP
      - 53:53/udp  # DNS UDP
      # - "8880:80"
    volumes:
      - adguard_data:/opt/adguardhome/work
      - adguard_conf:/opt/adguardhome/conf
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.adguard.rule=Host(`adguard.jgalabs.dk`)
        - traefik.http.routers.adguard.tls=true
        - traefik.http.routers.adguard.entrypoints=websecure
        - traefik.http.routers.adguard.tls.certresolver=cfresolver
        - traefik.http.services.adguard.loadbalancer.server.port=80
        - traefik.http.routers.adguard.service=adguard
    networks: [traefik_public]
secrets:
  cf_dns_api_token:
    external: true
volumes:
  adguard_data:
  adguard_conf:
  letsencrypt:
networks:
  traefik_public:
    name: traefik_public
    driver: overlay
    attachable: true
