---
services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    networks: [traefik, hoarder]
    volumes: [data:/data]
    ports: [3000:3000]
    env_file: [.env-hoarder]
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
    deploy:
      replicas: 0
      labels:
        - traefik.docker.lbswarm=true
        - sablier.enable=true
        - sablier.group=hoarder
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 1
        order: stop-first
        failure_action: pause
        delay: 10s
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    networks: [hoarder]
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    deploy:
      replicas: 0
      labels: [sablier.enable=true, sablier.group=hoarder]
  meilisearch:
    image: getmeili/meilisearch:v1.11.1
    networks: [hoarder]
    env_file: [.env-hoarder]
    environment:
      MEILI_NO_ANALYTICS: 'true'
    volumes: [meilisearch:/meili_data]
    deploy:
      replicas: 0
      labels: [sablier.enable=true, sablier.group=hoarder]
volumes:
  meilisearch:
  data:
networks:
  hoarder:
  traefik:
    name: traefik_public
    external: true
