---
services:
  dozzle:
    profiles: [apps, all]
    image: amir20/dozzle:v8.12.1
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
    networks: [traefik_public]
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
      - sablier.enable=true
      - sablier.group=dozzle
      - homepage.group=Developer
      - homepage.name=Dozzle
      - homepage.icon=dozzle.png
      - homepage.href=https://dozzle.${DOMAIN:-traefik.me}
      - homepage.description=Read system logs when troubleshooting
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
networks:
  traefik_public:
    name: traefik_public
    driver: bridge
    attachable: true
