---
services:
  omni-tools:
    profiles: [apps, all]
    image: iib0011/omni-tools:0.1.0
    restart: unless-stopped
    networks: [traefik_public]
    labels:
      - sablier.enable=true
      - sablier.group=omni-tools
      - homepage.group=Utilities
      - homepage.name=Omni Tools
      - homepage.icon=omni-tools.png
      - homepage.href=https://omni.${DOMAIN:-traefik.me}
      - homepage.description=General utilities for everyday tasks
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
networks:
  traefik_public:
    name: traefik_public
    driver: bridge
    attachable: true
