---
services:
  vert:
    profiles: [apps, all]
    image: ghcr.io/vert-sh/vert@sha256:c604d357e44dce6020391b6bd8d20e4f5d35e3778ecf58bbccbd8fdc6792eaf4
    restart: always
    environment:
      - PUB_HOSTNAME=vert.${DOMAIN:-traefik.me}
      - PUB_ENV=production
    networks: [traefik_public]
    labels:
      - sablier.enable=true
      - sablier.group=vert
      - homepage.group=Utilities
      - homepage.name=VERT
      - homepage.icon=https://raw.githubusercontent.com/VERT-sh/VERT/main/src/lib/components/visual/svg/Logo.svelte
      - homepage.href=https://vert.${DOMAIN:-traefik.me}
      - homepage.description=Convert files locally in your browser
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
networks:
  traefik_public:
    name: traefik_public
    driver: bridge
    attachable: true
