---
http:
  routers:
    dumbassets:
      rule: Host(`assets.{{ env "DOMAIN" }}`)
      entrypoints: [websecure]
      service: dumbassets
      middlewares: [sablier-dumbassets@file, startup-retry@file]
  services:
    dumbassets:
      loadBalancer:
        servers:
          - url: http://dumbassets:3000/
  middlewares:
    sablier-dumbassets:
      plugin:
        sablier:
          group: dumbassets
          dynamic:
            displayName: DumbAssets
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 30m
