---
http:
  routers:
    ha:
      rule: Host(`ha.{{ env "DOMAIN" }}`)
      entrypoints: ['{{ env "TRAEFIK_ENTRYPOINT" }}']
      service: ha
  services:
    ha:
      loadBalancer:
        serversTransport: ha-timeouts
        servers:
          - url: http://ha:8123/
  serversTransports:
    ha-timeouts:
      forwardingTimeouts:
        dialTimeout: 5s
        responseHeaderTimeout: 15s
