---
http:
  routers:
    hermes:
      rule: Host(`hermes.{{ env "DOMAIN" }}`)
      entrypoints: [websecure]
      service: hermes
      middlewares: [netbird-users-only@file, startup-retry@file]
  services:
    hermes:
      loadBalancer:
        servers:
          - url: http://hermes:9119/
