---
http:
  routers:
    jellyfin:
      rule: Host(`jellyfin.{{ env "DOMAIN" }}`)
      entrypoints: [websecure]
      service: jellyfin
      middlewares: [sablier-jellyfin@file, startup-retry@file]
  services:
    jellyfin:
      loadBalancer:
        servers:
          # - url: http://jellyfin:80  # jellyfin-vue
          - url: http://jellyfin:8096/  # regular
  middlewares:
    sablier-jellyfin:
      plugin:
        sablier:
          group: jellyfin
          dynamic:
            displayName: service
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 30m
