---
http:
  routers:
    listmonk:
      rule: Host(`listmonk.{{ env "DOMAIN" }}`)
      entrypoints: ['{{ env "TRAEFIK_ENTRYPOINT" }}']
      service: listmonk
  services:
    listmonk:
      loadBalancer:
        servers:
          - url: http://listmonk:9000/
