---
http:
  routers:
    speedtest:
      rule: Host(`speed.{{ env "DOMAIN" }}`)
      entrypoints: [websecure]
      service: speedtest
      middlewares: [sablier-speedtest@file, startup-retry@file]
  services:
    speedtest:
      loadBalancer:
        servers:
          - url: http://speedtest-tracker:80/
  middlewares:
    sablier-speedtest:
      plugin:
        sablier:
          group: speedtest
          dynamic:
            displayName: service
            refreshFrequency: 2s
            showDetails: 'true'
            theme: ghost
          sablierUrl: http://sablier:10000
          sessionDuration: 30m
