---
http:
  routers:
    whoami:
      rule: Host(`whoami.{{ env "DOMAIN" }}`)
      entrypoints: [websecure]
      service: whoami
      middlewares: [sablier-default@file, startup-retry@file]
  services:
    whoami:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: http://whoami/
