---
name: pre-commit auto-fix (uv)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 17 3 * * 1
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: pre-commit-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run-pre-commit:
    name: Run pre-commit (uvx) and open PR if changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up uv and cache
        uses: hynek/setup-cached-uv@v2
        with:
          cache-dependency-path: .pre-commit-config.yaml
      - name: Run pre-commit with uvx
        run: |
          # Run all hooks across the repo; allow modifications without failing the job
          uvx pre-commit run -a || true
      - name: Check for changes
        id: git_diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Create Pull Request with changes
        if: steps.git_diff.outputs.changed == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ci/pre-commit
          title: 'chore(pre-commit): auto-fix via pre-commit (uv)'
          body: |
            This PR was automatically generated by the pre-commit workflow.
            It runs all configured pre-commit hooks using uvx (via hynek/setup-cached-uv@v2) and commits any resulting fixes.
          commit-message: |
            chore(pre-commit): auto-fix via pre-commit (uv) [skip ci]
            Co-authored-by: openhands <openhands@all-hands.dev>
          delete-branch: true
          signoff: false
      - name: Enable auto-merge for the PR
        if: steps.cpr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
