name: yamlfix auto-format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: "17 3 * * 1"  # Every Monday at 03:17 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: yamlfix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-yamlfix:
    name: Run yamlfix and open PR if changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit yamlfix

      - name: Run yamlfix via pre-commit
        run: |
          # Run only the yamlfix hook to respect repo excludes
          pre-commit run yamlfix -a || true

      - name: Check for changes
        id: git_diff
        run: |
          if git diff --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with changes
        if: steps.git_diff.outputs.changed == 'true'
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ci/yamlfix
          title: "chore(yamlfix): auto-format YAML"
          body: |
            This PR was automatically generated by the yamlfix workflow.

            It applies formatting fixes to YAML files using the yamlfix tool, while respecting the repository's pre-commit configuration.
          commit-message: |
            chore(yamlfix): auto-format YAML [skip ci]

            Co-authored-by: openhands <openhands@all-hands.dev>
          add-paths: |
            **/*.yml
            **/*.yaml
          delete-branch: true
          signoff: false

      - name: Enable auto-merge for the PR
        if: steps.cpr.outputs.pull-request-number
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
